name: localizer
reportingTeam: cia-dev-tooling
description: ""
oss: true
slack: ""
library: true
commands:
  - localizer
releaseType: ""
deployTo:
  environments: []
arguments:
  dependencies:
    optional: []
    required: []
  description: ""
  reportingTeam: cia-dev-tooling
  type: []
modules:
  - url: https://github.com/getoutreach/stencil-base
    version: ""
