name: localizer
reportingTeam: fnd-dtss
description: A no-frills local development approach for Kubernetes powered Developer Environments.
oss: true
slack: ""
library: true
commands:
  - localizer
circleAPIKey: ""
releaseType: ""
deployTo:
  environments: []
arguments:
  circleAPIKey: ""
  commands:
    - localizer
  dependencies:
    optional: []
    required: []
  description: A no-frills local development approach for Kubernetes powered Developer Environments.
  grpcClients: []
  opslevel:
    confluenceSpaceKey: DTSS
    designDocumentLink: ""
  oss: true
  releaseOptions:
    allowMajorVersions: null
    allowPrereleases: false
  reportingTeam: fnd-dtss
  type:
    - library
modules:
  - name: github.com/getoutreach/stencil-base
    version: ""
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: DTSS
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
